pmndrs/koota

- packages/react/src/hooks/use-query.ts
- packages/react/tests/hooks.test.tsx
Note that `useQuery` returns the same `QueryResult` every time, but updates its entities as additions and removals happen.
> 🐛 react: useQuery propertly updates, returns a QueryResult

- README.md
- benches/apps/boids/src/actions.ts
- benches/apps/boids/src/systems/apply-forces.ts
- benches/apps/boids/src/systems/avoid-edges.ts
- benches/apps/boids/src/systems/move-boids.ts
- benches/apps/boids/src/systems/sync-three-object.ts
- benches/apps/boids/src/systems/update-alignment.ts
- benches/apps/boids/src/systems/update-coherence.ts
- benches/apps/boids/src/systems/update-neighbors.ts
- benches/apps/boids/src/systems/update-separation.ts
- benches/apps/boids/src/systems/update-spatial-hashing.ts
- benches/apps/boids/src/traits/neighbors.ts
- benches/apps/boids/src/traits/position.ts
- benches/apps/boids/src/traits/spatial-hash-map.ts
- benches/apps/boids/src/traits/velocity.ts
- benches/apps/boids/src/world.ts
- packages/core/src/entity/types.ts
- packages/core/src/query/query-result.ts
- packages/core/src/query/types.ts
- packages/core/src/trait/trait.ts
- packages/core/src/trait/types.ts
- packages/core/src/trait/utils/create-accessors.ts
- packages/core/src/trait/utils/create-store.ts
- packages/core/src/utils/shallow-equal.ts
- packages/core/src/world/world.ts
- packages/core/tests/query.test.ts
- packages/core/tests/trait.test.ts
This PR enables creating AoS trait stores using callbacks.
```js
// AoS store
const Position = trait(() => ({ x: 0, y: 0, z: 0 }))
// SoA store
const Position = trait({ x: 0, y: 0, z: 0 })
```
While SoA stores are recommended for performance, AoS is very useful for compatibility with libraries and class instances in general.
```js
const Position = trait(() => THREE.Vector3())
```
I banged out the code to make it work but it needs refactoring with fresh eyes before it goes into production.
> ✨ core: create AoS trait stores

- packages/core/src/world/world.ts
Signed-off-by: Kris Baumgartner <kjbaumgartner@gmail.com>
> 🐛 core: onChange properly registers traits being tracked

- packages/core/src/entity/entity-methods-patch.ts
- packages/core/src/entity/types.ts
- packages/core/tests/entity.test.ts
Signed-off-by: Kris Baumgartner <kjbaumgartner@gmail.com>
> ✨ core: entity set can take a callback with previous state passed in

- packages/core/src/entity/entity.ts
- packages/core/src/entity/types.ts
- packages/core/src/query/modifiers/changed.ts
- packages/core/src/relation/relation.ts
- packages/core/src/relation/types.ts
- packages/core/tests/relation.test.ts
Hi! 👋 
Was trying to fix a different issue, but it seems that it was already resolved. Meanwhile, I found a possible solution to the incompatible type of `Wildcard` in some scenarios.
- `Wildcard` is both an acceptable `RelationTarget` as well as a callable, which is hard to achieve with the current `Relation<any> | string` type.
- `RelationTarget` is not broad enough to accept any Relation, as `Wildcard` differs on the type-level, yet is assignable to any `Relation` (see screenshot below).
- An additional test for querying relations with specific targets.
> fix: Wildcard relation is a valid RelationTarget.

- packages/core/src/relation/types.ts
The biggest PR of them all 🌋🦕
- Not allowing arbitrary strings into relations
- Better auto-complete
> 🏷️ core: wildcard string typed as `'*'`

- README.md
- packages/core/src/query/query-result.ts
- packages/core/src/query/query.ts
- packages/core/src/query/types.ts
- packages/core/src/world/world.ts
- packages/core/tests/query.test.ts
By default, `updateEach` will automatically turn on change detection for traits that are being tracked via `onChange` or the `Changed` modifier. If you want to silence change detection for a loop or force it to always run, you can do so with an options config.
```js
// Setting changeDetection to 'never' will silence it, triggering no change events
world.query(Position, Velocity).updateEach(([position, velocity]) => {
}, { changeDetection: 'never' });
// Setting changeDetection to 'always' will ignore selective tracking and always emit change events for all traits that are mutated
world.query(Position, Velocity).updateEach(([position, velocity]) => {
}, { changeDetection: 'never' });
```
> ✨ core: auto change detection for updateEach

- packages/core/src/entity/entity-methods-patch.ts
Signed-off-by: Kris Baumgartner <kjbaumgartner@gmail.com>
> 🐛 core: entity get works with multi-generation entities again

- README.md
- packages/core/src/query/query.ts
- packages/core/tests/query.test.ts
This PR makes a rather simple change but clarifies internal concepts. 
Perviously querying with empty params returned no entities, ie`world.query()`. Now it returns all queryable entities.
What are queryable entities? We have a system level tag called `IsExcluded` that can be used to make any entity non-queryable. This is used interally for world entities but also for possible features like prefabs and inheritance. These entities are not queryable, so you can add trais to the world without worrying about it polluting queries.
To get all entities, even non-queryable ones you can access `world.entities`.
Signed-off-by: Kris Baumgartner <kjbaumgartner@gmail.com>
> 💥 core: queries with empty params return all queryable entities

- packages/core/src/entity/types.ts
- packages/core/src/query/query.ts
- packages/core/src/relation/relation.ts
- packages/core/src/trait/types.ts
This fixes the relation store get type with entity get method.
```js
const Contains = relation({ store: { amount: 0 } });
const gold = world.spawn();
const entity = world.spawn(Contains(gold));
const amount = entity.get(Contains(gold))!; // Should be type { amount: number }
```
> Fix relation store get type with get method

- packages/core/src/query/query.ts
- packages/react/src/hooks/use-query.ts
- packages/react/tests/query.test.tsx
This PR makes `useQuery` immutable, so it returns a new array on each update and also makes it so `useQuery` only rerenders on effect if there is an actual change in the query result.
This conforms to React expectations and should fix a lot of confusion users have been encountering.
> Make `useQuery` immutable and more stable

- benches/apps/n-body-react/src/App.tsx
- packages/core/src/entity/entity-methods-patch.ts
- packages/core/src/query/modifiers/added.ts
- packages/core/src/query/modifiers/changed.ts
- packages/core/src/query/modifiers/removed.ts
- packages/core/src/query/utils/cache-query.ts
- packages/core/src/universe/universe.ts
- packages/core/src/world/world.ts
- packages/core/tests/world.test.ts
This PR makes it so `universe` no longer holds a strong reference on worlds allowing them to be GCed. A finalization registry is used to release its ID. This allows for patterns like creating a world in a `useMemo` without side effects if it is discarded immediately.
> ✨ core: world is now GC safe

- README.md
- packages/react/src/index.ts
- packages/react/src/world/default-world.ts
- packages/react/src/world/use-world.ts
- packages/react/tests/world.test.tsx
Removes the default world from the React package, making it a requirement to use `WorldProvider`. I thought it would make it easier to get started with one less step, but it introduced edge cases because it is easy to forget there is an extra world floating around.
> 💥 react: remove default world

- README.md
- packages/core/src/world/world.ts
- packages/core/tests/world.test.ts
Adds some options the world reset method. For example, to preserve subscriptions to queries.
> Add world reset options

- README.md
- packages/core/src/query/query.ts
- packages/core/src/world/world.ts
- packages/core/tests/world.test.ts
- packages/react/src/hooks/use-query.ts
- packages/react/src/world/use-world.ts
- packages/react/tests/query.test.tsx
- packages/react/tests/trait.test.tsx
Remove the reset options and add an internal reset subscription API that `useQuery` hooks into for reactivity.
> Fix world reset reactivity

- packages/core/src/query/query.ts
- packages/core/src/query/utils/cache-query.ts
- packages/core/src/world/world.ts
- packages/core/tests/query.test.ts
This caused `cacheQuery` to fail when run before a world was created, among other possible bugs.
> 🐛  core: system traits get properly registered with new worlds

- packages/publish/tsup.config.ts
When running vite as my bundler, koota is running under strict mode.
When using metro with expo dom components koota is not running under strict mode.
When `this` is evaluated in Number.prototype.add in strict mode it will be a number.
When `this` is evaluated in Number.prototype.add without strict mode, it is coerced into an object, and that object is then used as the lookup in the Set where that object is not in the Set, the valueOf that object is.
See: https://262.ecma-international.org/5.1/#sec-C
Philosophcally it is a slightly painful pr to make, however, if bundlers in 2025 are going to run esm code without strict mode enabled, we should help them to have a chance.
> fix: emit "use strict" everywhere to thwart bad bundlers

- README.md
Saw this project on Hacker News—really cool work! While browsing the README, I noticed a couple minor typos:
"no queryable" → "not queryable"
"enttiy" → "entity"
This PR fixes those to improve readability and polish.
> Fix typos in README (no queryable → not queryable, enttiy → entity)

- packages/core/src/world/world.ts
- packages/core/tests/world.test.ts
This is fixing a bug in the `world.reset()` method when we have relationships with auto-remove targets.
> fix: ensure entities are only destroyed when present

- packages/core/src/query/query-result.ts
- packages/core/src/query/query.ts
- packages/core/tests/query-modifiers.test.ts
This PR fixes a couple of bugs by resetting bit masks for entities returned from tracking queries
> Reset bit masks after executing tracking queries

- README.md
- packages/core/src/index.ts
- packages/core/tests/actions.test.ts
- packages/core/tests/entity.test.ts
- packages/core/tests/query-modifiers.test.ts
- packages/core/tests/query.test.ts
- packages/core/tests/relation.test.ts
- packages/core/tests/trait.test.ts
- packages/core/tests/world.test.ts
Adds missing exports found in tests, `unpackEntity`, `getStore` and `IsExcluded.` Also makes the tests import from index to make sure it only tests public APIs.
> Add missing exports

- README.md
- packages/core/src/trait/trait.ts
- packages/core/tests/relation.test.ts
- packages/publish/tests/core/trait.test.ts
For example:
```js
player.add(Likes(apple))
player.add(Likes(banana))
// Remove all Likes relations
player.remove(Likes('*'))
player.has(apple) // false
player.has(banana) // false
```
> feat: remove all relation targets with a wildcard

- pnpm-lock.yaml
Dep tree had a mismatch, see: https://github.com/mrdoob/three.js/pull/30934 and https://github.com/pmndrs/three-stdlib/pull/419. Having the older stdlib made freshly  cloned/installed repo fail when running commands such as `pnpm run app boids`
I opted to just bump the stdlib to the version that had the fix, rather than the latest version available as that felt safer 😛
Note also that some lines re react types got updated as well, which makes the diff less clean than I would have liked but these appear to be in keeping with the dep specification. 
Running with this diff allowed me to run the examples on a new machine without error, as I was able to previously.
Thanks!
> Chore  three-stdlib

- README.md
This PR fixes a typo in de doc (README.md)
`usQueryFirst` -> `useQueryFirst`
> fix typo into README

- packages/core/src/query/modifiers/changed.ts
- packages/core/tests/query-modifiers.test.ts
- packages/publish/tests/core/query-modifiers.test.ts
Initial query population logic could previously produce incorrect results due to `setChanged` using `changedMask` in a different way, compared to other places:
- In `Query`, when we work with individual `changedMask` (from `ctx.changedMasks.get(id)!`), we use it as `changedMask[generationId][eid]`
- In `setChanged`, when we iterate over `changedMask` (from `ctx.changedMasks.values()`), we use it as `changedMask[eid][traitId]`
In this PR we ensure `changedMask` usage stays consistent with existing patterns
> fix: update setChanged logic to correctly populate changedMask

- README.md
- packages/core/src/entity/types.ts
- packages/core/src/query/types.ts
- packages/core/src/trait/types.ts
- packages/core/src/world/world.ts
- packages/core/tests/world.test.ts
- packages/react/src/hooks/use-trait-effect.ts
- packages/react/src/hooks/use-trait.ts
- packages/react/tests/trait.test.tsx
- pnpm-workspace.yaml
`TraintInstance` isn't really a good term to use. Instance of overloaded and usually refers to a reference while what is returned from `entity.get(Trait)` is a snapshot in the case of an SoA store and ref in the case of an AoS store. More accurate is record since we are turning what is in the virtual database row. 
Addresses: https://github.com/pmndrs/koota/issues/156
> chore: rename TraitInstance to TraitRecord

- packages/core/src/trait/trait.ts
- packages/core/tests/trait.test.ts
- packages/publish/tests/core/trait.test.ts
- packages/publish/tests/core/world.test.ts
- packages/publish/tests/react/trait.test.tsx
If multiple traits were passed into `add` and one was already on the entity then there would be an early exit and the rest would not be added. Same for `remove` and if one trait was not on the entity, there would be an early exit.
> 🐛 core: trait add and remove would early exit with variadic args
